"""Initial migration

Revision ID: 9b52e28de463
Revises: 
Create Date: 2026-03-02 23:48:36.405777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b52e28de463'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'description')
    op.add_column('courses', sa.Column('hero_video_url', sa.String(length=500), nullable=True))
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'hero_video_url')
    op.add_column('chapters', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
